version: '3.1'

services:
    wordpress:
        image: wordpress:quads
        container_name: wordpress
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_PASSWORD: password
        links:
            - mariadb:db

    mariadb:
        image: mariadb:quads
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
